server:
  servlet:
    context-path: /api
#  port: 8888
  port: ${SPRING_PROFILES_PORT}

spring:
  profiles:
#    active: local
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: off

logging:
  file.name: logs/nta-bookstore.log
  pattern:
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: ERROR
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    nta.bookstore.api: DEBUG

file:
  uploadDirectory: images