spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nta_bookstore
    username: xxx
    password: xxx

app:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      # seconds
      valid-time: 36000

mail-sender:
  host: smtp.gmail.com
  port: 587
  email: xxx
  password: xxx