version: "3.8"
name: nta-bookstore
services:
  db:
    container_name: book_store_postgres
    image: mysql:8.0.28
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=lovecan148
    volumes:
      - db-data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
